language: node_js
node_js:
  - node

services:
  - postgresql

before_script:
  - psql -c 'create database authors_haven_test;' -U postgres

script:
  - npm test
after_success:
  - npm run coveralls
  - npm run coverage
  - npm run report-coverage
